/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import DomainModels.GioHang;
import DomainModels.KhachHang;
import DomainModels.NhanVien;
import Repositories.IKhachHangRepository;
import Repositories.INhanVienRepository;
import Repositories.KhachHangRepository;
import Repositories.NhanVienRepository;
import Services.GioHangService;
import Services.IGioHangService;
import ViewsModels.QLGioHang;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class FrmGioHang extends javax.swing.JFrame {

    /**
     * Creates new form FrmGioHang
     */
    IGioHangService iGioHangService;
    IKhachHangRepository iKhachHangRepository;
    INhanVienRepository iNhanVienRepository;
    DefaultComboBoxModel<String> cbBoxModel;
    DefaultTableModel model;
    private int totalPage;
    private int totalGioHang;
    private final int pageSize;
    private int currentPage;

    public FrmGioHang() {
        initComponents();
        setLocationRelativeTo(this);
        iGioHangService = new GioHangService();
        iKhachHangRepository = new KhachHangRepository();
        iNhanVienRepository = new NhanVienRepository();
        model = (DefaultTableModel) tblGioHang.getModel();
        getCBXKhachHang();
        getCBXNhanVien();
        currentPage = 1;
        pageSize = 5;
        loadTable(getCurrentPage());
    }

    private void getCBXKhachHang() {
        cbBoxModel = (DefaultComboBoxModel<String>) cbxKH.getModel();
        List<KhachHang> list = iKhachHangRepository.findAll();
        cbBoxModel.removeAllElements();
        for (KhachHang kh : list) {
            cbBoxModel.addElement(kh.getTen());
        }
    }

    private void getCBXNhanVien() {
        cbBoxModel = (DefaultComboBoxModel<String>) cbxNV.getModel();
        List<NhanVien> list = iNhanVienRepository.findAll();
        cbBoxModel.removeAllElements();
        for (NhanVien nv : list) {
            cbBoxModel.addElement(nv.getTen());
        }
    }

    private void loadTable(List<QLGioHang> gioHangs) {
        model.setRowCount(0);
        for (QLGioHang gh : gioHangs) {
            model.addRow(new Object[]{gh.getId(), gh.getKhachHang().getTen(), gh.getNhanVien().getTen(), gh.getMa(), gh.getNgayTao(),
                gh.getNgayThanhToan(), gh.getTenNguoiNhan(), gh.getDiaChi(), gh.getSdt(), gh.getTinhTrangString()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMa5 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbxKH = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbxNV = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNgayTao = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        j = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtThanhToan = new javax.swing.JTextField();
        txtTennguoiNhan = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        rbDaThanhToan = new javax.swing.JRadioButton();
        rbChuaThanhToan = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGioHang = new javax.swing.JTable();
        btnNew = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lbCurrentPage = new javax.swing.JLabel();
        btnTruoc = new javax.swing.JButton();
        btnSau = new javax.swing.JButton();
        lbTotalGioHang = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Id:");

        txtId.setEditable(false);

        jLabel2.setText("Tên KH:");

        cbxKH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Tên NV:");

        cbxNV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Mã:");

        jLabel5.setText("Ngày tạo:");

        jLabel6.setText("Ngày thanh toán:");

        j.setText("Tên người nhận:");

        jLabel8.setText("Địa chỉ:");

        jLabel9.setText("SĐT:");

        jLabel10.setText("Tình Trạng:");

        buttonGroup1.add(rbDaThanhToan);
        rbDaThanhToan.setText("Đã thanh toán");

        buttonGroup1.add(rbChuaThanhToan);
        rbChuaThanhToan.setText("Chưa thanh toán");

        tblGioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Tên KH", "Tên NV", "Mã", "Ngày tạo", "Ngày thanh toán", "Tên người nhận", "Địa chỉ", "SĐT", "Tình trạng"
            }
        ));
        tblGioHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGioHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGioHang);

        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        lbCurrentPage.setText("1/1");

        btnTruoc.setText("<");
        btnTruoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTruocActionPerformed(evt);
            }
        });

        btnSau.setText(">");
        btnSau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSauActionPerformed(evt);
            }
        });

        lbTotalGioHang.setText("Total GioHang:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(35, 35, 35))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel3))
                                        .addGap(25, 25, 25)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(txtMa)
                                    .addComponent(txtNgayTao)
                                    .addComponent(cbxNV, 0, 119, Short.MAX_VALUE)
                                    .addComponent(cbxKH, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(84, 84, 84)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(51, 51, 51)
                                        .addComponent(rbDaThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbChuaThanhToan))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(j)
                                                .addGap(26, 26, 26))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel8))
                                                .addGap(21, 21, 21)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtTennguoiNhan, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                                            .addComponent(txtDiaChi, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtSDT)
                                            .addComponent(txtThanhToan)))))
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btnTruoc, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(lbCurrentPage, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSau, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(lbTotalGioHang)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j)
                    .addComponent(jLabel2)
                    .addComponent(cbxKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTennguoiNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel3)
                            .addComponent(cbxNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(rbDaThanhToan)
                    .addComponent(rbChuaThanhToan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNew)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnClear))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCurrentPage)
                    .addComponent(btnTruoc)
                    .addComponent(btnSau)
                    .addComponent(lbTotalGioHang))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        QLGioHang qlgh = validateGioHang();
        if (qlgh != null) {
            List<QLGioHang> list = iGioHangService.getAllGioHangs();
            if (list.size() > 0) {
                for (QLGioHang gh : list) {
                    if (qlgh.getMa().equalsIgnoreCase(gh.getMa())) {
                        JOptionPane.showMessageDialog(this, "Mã đã tồn tại");
                        return;
                    }
                }
            }
            JOptionPane.showMessageDialog(this, iGioHangService.saveGioHang(qlgh));
            loadTable(getCurrentPage());
        } else {
            JOptionPane.showMessageDialog(this, "Thêm mới thất bại");
        }
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int selectRow = tblGioHang.getSelectedRow();
        if (selectRow < 0) {
            JOptionPane.showMessageDialog(this, "Chọn 1 dòng trên bảng");
            return;
        }
        QLGioHang qlgh = validateGioHang();
        qlgh.setId(tblGioHang.getValueAt(selectRow, 0).toString());
        if (qlgh != null) {
            JOptionPane.showMessageDialog(this, iGioHangService.updateGioHang(qlgh));
            loadTable(getCurrentPage());
        }else{
            JOptionPane.showMessageDialog(this,"Sửa thất bại");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectRow = tblGioHang.getSelectedRow();
        if (selectRow < 0) {
            JOptionPane.showMessageDialog(this, "Chọn 1 dòng trên bảng");
            return;
        }
        int kq = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (kq == JOptionPane.YES_OPTION) {
            String id = tblGioHang.getValueAt(selectRow, 0).toString();
            JOptionPane.showMessageDialog(this, iGioHangService.deleteGioHang(id));
            clear();
            currentPage = 1;
            loadTable(getCurrentPage());
        } else {
            JOptionPane.showMessageDialog(this, "Xóa thất bại");
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void tblGioHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGioHangMouseClicked
        // TODO add your handling code here:
        int selectRow = tblGioHang.getSelectedRow();
        txtId.setText(tblGioHang.getValueAt(selectRow, 0).toString());
        cbxKH.setSelectedItem(tblGioHang.getValueAt(selectRow, 1));
        cbxNV.setSelectedItem(tblGioHang.getValueAt(selectRow, 2));
        txtMa.setText(tblGioHang.getValueAt(selectRow, 3).toString());
        txtNgayTao.setText(tblGioHang.getValueAt(selectRow, 4).toString());
        txtThanhToan.setText(tblGioHang.getValueAt(selectRow, 5).toString());
        txtTennguoiNhan.setText(tblGioHang.getValueAt(selectRow, 6).toString());
        txtDiaChi.setText(tblGioHang.getValueAt(selectRow, 7).toString());
        txtSDT.setText(tblGioHang.getValueAt(selectRow, 8).toString());
        if (tblGioHang.getValueAt(selectRow, 9).equals(rbDaThanhToan.getText())) {
            rbDaThanhToan.setSelected(rootPaneCheckingEnabled);
        }
    }//GEN-LAST:event_tblGioHangMouseClicked

    private void btnTruocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTruocActionPerformed
        // TODO add your handling code here:
        currentPage--;
        if(currentPage <= 0){
            currentPage = totalPage;
        }
        loadTable(getCurrentPage());
    }//GEN-LAST:event_btnTruocActionPerformed

    private void btnSauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSauActionPerformed
        // TODO add your handling code here:
        currentPage++;
        if(currentPage > totalPage){
            currentPage = 1;
        }
        loadTable(getCurrentPage());
    }//GEN-LAST:event_btnSauActionPerformed

    private QLGioHang validateGioHang() {
        String id = "";
        String tenKH = (String) cbxKH.getSelectedItem();
        KhachHang kh = iKhachHangRepository.getKhachHangTheoName(tenKH);
        String tenNV = (String) cbxNV.getSelectedItem();
        NhanVien nv = iNhanVienRepository.layNhanVienTheoName(tenNV);
        String ma = txtMa.getText();
        if (ma.isBlank()) {
            JOptionPane.showMessageDialog(this, "Không được để trống mã");
            return null;
        }
        SimpleDateFormat dft = new SimpleDateFormat("yyyy-MM-dd");
        String ngayTaoString = txtNgayTao.getText();
        if (ngayTaoString.isBlank()) {
            JOptionPane.showMessageDialog(this, "Ngày tạo không được để trống");
        }
        Date ngayTao;
        try {
            ngayTao = (Date) dft.parse(ngayTaoString);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ngày tạo không đúng định dạng(yyyy-MM-dd)");
            return null;
        }
        String ngayThanhToanString = txtThanhToan.getText();
        if (ngayThanhToanString.isBlank()) {
            JOptionPane.showMessageDialog(this, "Ngày thanh toán không được để trống");
        }
        Date ngayThanhToan;
        try {
            ngayThanhToan = (Date) dft.parse(ngayThanhToanString);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ngày thanh toán không đúng định dạng(yyyy-MM-dd)");
            return null;
        }
        String tenNguoiNhan = txtTennguoiNhan.getText();
        if (tenNguoiNhan.isBlank()) {
            JOptionPane.showMessageDialog(this, "Tên người nhận không được để trống");
            return null;
        }
        String diaChi = txtDiaChi.getText();
        if (diaChi.isBlank()) {
            JOptionPane.showMessageDialog(this, "Địa chỉ không được để trống");
            return null;
        }
        String sdt = txtSDT.getText();
        if (sdt.isBlank()) {
            JOptionPane.showMessageDialog(this, "SĐT không được để trống");
            return null;
        }
        if (!rbDaThanhToan.isSelected() && !rbChuaThanhToan.isSelected()) {
            JOptionPane.showMessageDialog(this, "Chưa chọn tình trạng");
            return null;
        }
        String tinhTrangString = rbDaThanhToan.isSelected() ? rbDaThanhToan.getText() : rbChuaThanhToan.getText();
        int tinhTrang = tinhTrangString.equalsIgnoreCase(rbDaThanhToan.getText()) ? 1 : 0;
        return new QLGioHang(id, kh, nv, ma, ngayTao, ngayThanhToan, tenNguoiNhan, diaChi, sdt, tinhTrang);
    }

    private void clear() {
        txtId.setText("");
        cbxKH.setSelectedIndex(0);
        cbxNV.setSelectedIndex(0);
        txtMa.setText("");
        txtNgayTao.setText("");
        txtThanhToan.setText("");
        txtTennguoiNhan.setText("");
        txtDiaChi.setText("");
        txtSDT.setText("");
        rbDaThanhToan.setSelected(rootPaneCheckingEnabled);
    }

    private List<QLGioHang> getCurrentPage() {
        totalGioHang = iGioHangService.getAllGioHangs().size();
        totalPage = (totalGioHang - 1) / pageSize + 1;
        lbCurrentPage.setText(currentPage+"/"+totalPage);
        lbTotalGioHang.setText("total GioHang:"+totalGioHang);
        int start = (currentPage -1)*pageSize;
        int end = currentPage*pageSize;
        if(end > totalGioHang){
            end = totalGioHang;
        }
        return iGioHangService.getAllGioHangs().subList(start, end);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGioHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGioHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGioHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGioHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGioHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSau;
    private javax.swing.JButton btnTruoc;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxKH;
    private javax.swing.JComboBox<String> cbxNV;
    private javax.swing.JLabel j;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCurrentPage;
    private javax.swing.JLabel lbTotalGioHang;
    private javax.swing.JRadioButton rbChuaThanhToan;
    private javax.swing.JRadioButton rbDaThanhToan;
    private javax.swing.JTable tblGioHang;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtMa5;
    private javax.swing.JTextField txtNgayTao;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTennguoiNhan;
    private javax.swing.JTextField txtThanhToan;
    // End of variables declaration//GEN-END:variables
}
