/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import DomainModels.ChiTietSP;
import DomainModels.HoaDon;
import Repositories.ChiTietSPRepository;
import Repositories.HoaDonChiTietRepository;
import Repositories.HoaDonRepository;
import Repositories.IChitietSPRepository;
import Repositories.IHoaDonChiTietRepository;
import Repositories.IHoaDonRepository;
import Services.HoaDonChiTietService;
import Services.IHoaDonChiTietService;
import ViewsModels.QLHoaDonChiTiet;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class FrmHoaDonChiTiet extends javax.swing.JFrame {

    /**
     * Creates new form FrmHoaDonChiTiet
     */
    IHoaDonRepository iHoaDonRepository;
    IChitietSPRepository iChitietSPRepository;
    IHoaDonChiTietService iHoaDonChiTietService;
    DefaultComboBoxModel<String> cbBoxModel;
    DefaultTableModel model;
    private int totalPage;
    private int totalHDCT;
    private final int pageSize;
    private int currentPage;

    public FrmHoaDonChiTiet() {
        initComponents();
        setLocationRelativeTo(this);
        iHoaDonRepository = new HoaDonRepository();
        iChitietSPRepository = new ChiTietSPRepository();
        iHoaDonChiTietService = new HoaDonChiTietService();
        getAllChiTietSP();
        getAllHD();
        currentPage = 1;
        pageSize = 5;
        model = (DefaultTableModel) tblHoaDonChiTiet.getModel();
        loadTable(getCurrentPage());
    }

    private void getAllHD() {
        List<HoaDon> list = iHoaDonRepository.getAllHoasDons();
        cbBoxModel = (DefaultComboBoxModel<String>) cbxMaHD.getModel();
        cbBoxModel.removeAllElements();
        for (HoaDon hd : list) {
            cbBoxModel.addElement(hd.getMa());
        }
    }

    private void getAllChiTietSP() {
        List<String> list = iChitietSPRepository.getAllTen();
        cbBoxModel = (DefaultComboBoxModel<String>) cbxTenSP.getModel();
        cbBoxModel.removeAllElements();
        for (String s : list) {
            cbBoxModel.addElement(s);
        }
    }

    private void loadTable(List<QLHoaDonChiTiet> list) {
        model.setRowCount(0);
        for (QLHoaDonChiTiet hdct : list) {
            model.addRow(new Object[]{hdct.getHoaDon().getMa(), iChitietSPRepository.getTen(hdct.getChiTietSP().getId()),
                hdct.getSoLuong(), hdct.getDonGia(), hdct.getThanhTien()});
        }
    }

    private QLHoaDonChiTiet validateHoaDonChiTiet() {
        String maHD = (String) cbxMaHD.getSelectedItem();
        HoaDon hd = iHoaDonRepository.getHoaDonTheoMa(maHD);
        String tenSP = (String) cbxTenSP.getSelectedItem();
        ChiTietSP chiTietSP = iChitietSPRepository.getChiTietSPTheoTen(tenSP);
        String soLuongString = txtSoLuong.getText();
        if (soLuongString.isBlank()) {
            JOptionPane.showMessageDialog(this, "không đưuọc để trống số lượng");
            return null;
        }
        int soLuong = 0;
        try {
            soLuong = Integer.valueOf(soLuongString);
            if (soLuong <= 0) {
                JOptionPane.showMessageDialog(this, "lỗi dữ liệu,soLuong > 0");
                return null;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Số lượng phải là kiểu số nguyên");
            return null;
        }
        String donGiaString = txtDonGia.getText();
        if (donGiaString.isBlank()) {
            JOptionPane.showMessageDialog(this, "không đưuọc để trống đơn giá");
            return null;
        }
        float donGia = 0;
        try {
            donGia = Float.valueOf(donGiaString);
            if (donGia <= 0) {
                JOptionPane.showMessageDialog(this, "lỗi dữ liệu,donGia > 0");
                return null;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Đơn giá phải là kiểu số ");
            return null;
        }
        return new QLHoaDonChiTiet(hd, chiTietSP, soLuong, donGia);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxMaHD = new javax.swing.JComboBox<>();
        cbxTenSP = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDonChiTiet = new javax.swing.JTable();
        btnNew = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jlbCurrentPage = new javax.swing.JLabel();
        btnTruoc = new javax.swing.JButton();
        btnSau = new javax.swing.JButton();
        jlbTotalHDCT = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbxMaHD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbxTenSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Mã HĐ:");

        jLabel2.setText("Tên SP:");

        jLabel3.setText("Số lượng:");

        jLabel4.setText("Đơn giá:");

        tblHoaDonChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã HĐ", "Tên SP", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ));
        tblHoaDonChiTiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonChiTietMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoaDonChiTiet);

        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jlbCurrentPage.setText("1/1");

        btnTruoc.setText("<");
        btnTruoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTruocActionPerformed(evt);
            }
        });

        btnSau.setText(">");
        btnSau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSauActionPerformed(evt);
            }
        });

        jlbTotalHDCT.setText("Total  HDCT:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbxTenSP, 0, 161, Short.MAX_VALUE)
                                    .addComponent(cbxMaHD, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                    .addComponent(txtDonGia)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnTruoc, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jlbCurrentPage)
                        .addGap(28, 28, 28)
                        .addComponent(btnSau, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jlbTotalHDCT, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNew)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnClear))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbCurrentPage)
                            .addComponent(btnTruoc)
                            .addComponent(btnSau))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlbTotalHDCT)
                        .addGap(23, 23, 23))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int selectRow = tblHoaDonChiTiet.getSelectedRow();
        if (selectRow < 0) {
            JOptionPane.showMessageDialog(this, "Chon 1 dong ten table");
            return;
        }
        QLHoaDonChiTiet qlhdct = validateHoaDonChiTiet();
        if (qlhdct != null) {
            JOptionPane.showMessageDialog(this, iHoaDonChiTietService.updateHoaDonChiTiet(qlhdct));
            loadTable(getCurrentPage());
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        QLHoaDonChiTiet hoaDonChiTiet = validateHoaDonChiTiet();
        if (hoaDonChiTiet != null) {
            List<QLHoaDonChiTiet> list = iHoaDonChiTietService.getAllHoaDonChiTiet();
            if(list.size() != 0){
                for(QLHoaDonChiTiet ghChiTiet:list){
                    if(hoaDonChiTiet.getHoaDon().getId().equalsIgnoreCase(ghChiTiet.getHoaDon().getId()) && hoaDonChiTiet.getChiTietSP().getId().equalsIgnoreCase(ghChiTiet.getChiTietSP().getId())){
                        JOptionPane.showMessageDialog(this,"Mã HD và ID CTSP đã tồn tại");
                        return;
                    }
                }
            }
            JOptionPane.showMessageDialog(this, iHoaDonChiTietService.saveHoaDonChiTiet(hoaDonChiTiet));
            loadTable(getCurrentPage());
        }
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectRow = tblHoaDonChiTiet.getSelectedRow();
        if (selectRow < 0) {
            JOptionPane.showMessageDialog(this, "Chon 1 dong ten table");
            return;
        }
        int kq = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (kq == JOptionPane.YES_OPTION) {
            String maHD = tblHoaDonChiTiet.getValueAt(selectRow, 0).toString();
            HoaDon hd = iHoaDonRepository.getHoaDonTheoMa(maHD);
            String tenSP = tblHoaDonChiTiet.getValueAt(selectRow, 1).toString();
            ChiTietSP chiTietSP = iChitietSPRepository.getChiTietSPTheoTen(tenSP);
            JOptionPane.showMessageDialog(this, iHoaDonChiTietService.deleteHoaDonChiTiet(hd.getId(), chiTietSP.getId()));
            loadTable(getCurrentPage());
            clear();
        } else {
            JOptionPane.showMessageDialog(this, "Xóa thất bại");
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void tblHoaDonChiTietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonChiTietMouseClicked
        // TODO add your handling code here:
        int selectRow = tblHoaDonChiTiet.getSelectedRow();
        cbxMaHD.setSelectedItem(tblHoaDonChiTiet.getValueAt(selectRow, 0));
        cbxTenSP.setSelectedItem(tblHoaDonChiTiet.getValueAt(selectRow, 1));
        txtSoLuong.setText(tblHoaDonChiTiet.getValueAt(selectRow, 2).toString());
        txtDonGia.setText(tblHoaDonChiTiet.getValueAt(selectRow, 3).toString());
    }//GEN-LAST:event_tblHoaDonChiTietMouseClicked

    private void btnTruocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTruocActionPerformed
        // TODO add your handling code here:
        currentPage--;
        if (currentPage <= 0) {
            currentPage = totalPage;
        }
        loadTable(getCurrentPage());
    }//GEN-LAST:event_btnTruocActionPerformed

    private void btnSauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSauActionPerformed
        // TODO add your handling code here:
        currentPage++;
        if (currentPage > totalPage) {
            currentPage = 1;
        }
        loadTable(getCurrentPage());
    }//GEN-LAST:event_btnSauActionPerformed

    private List<QLHoaDonChiTiet> getCurrentPage() {
        totalHDCT = iHoaDonChiTietService.getAllHoaDonChiTiet().size();
        totalPage = (totalHDCT - 1) / pageSize + 1;
        jlbCurrentPage.setText(currentPage + "/" + totalPage);
        jlbTotalHDCT.setText("total GioHang:" + totalHDCT);
        int start = (currentPage - 1) * pageSize;
        int end = currentPage * pageSize;
        if (end > totalHDCT) {
            end = totalHDCT;
        }
        return iHoaDonChiTietService.getAllHoaDonChiTiet().subList(start, end);
    }

    private void clear() {
        cbxMaHD.setSelectedIndex(0);
        cbxTenSP.setSelectedIndex(0);
        txtSoLuong.setText("");
        txtDonGia.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmHoaDonChiTiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmHoaDonChiTiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmHoaDonChiTiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmHoaDonChiTiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmHoaDonChiTiet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSau;
    private javax.swing.JButton btnTruoc;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbxMaHD;
    private javax.swing.JComboBox<String> cbxTenSP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbCurrentPage;
    private javax.swing.JLabel jlbTotalHDCT;
    private javax.swing.JTable tblHoaDonChiTiet;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtSoLuong;
    // End of variables declaration//GEN-END:variables
}
