/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import DomainModels.ChucVu;
import DomainModels.CuaHang;
import DomainModels.NhanVien;
import Repositories.ChucVuRepository;
import Repositories.CuaHangRepository;
import Repositories.IChucVuRepository;
import Repositories.ICuaHangRepository;
import Repositories.INhanVienRepository;
import Repositories.NhanVienRepository;
import Services.ChucVuService;
import Services.CuaHangService;
import Services.IChucVuService;
import Services.ICuaHangService;
import Services.INhanVienService;
import Services.NhanVienService;
import ViewsModels.QLChucVu;
import ViewsModels.QLCuaHang;
import ViewsModels.QLNhanVien;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class FrmNhanVien extends javax.swing.JFrame {

    /**
     * Creates new form FrmQLCuaHang
     */
    private ICuaHangRepository iCuaHangRepository;
    private IChucVuRepository iChucVuRepository;
    private INhanVienRepository iNhanVienRepository;
    DefaultComboBoxModel<String> model1;
    DefaultTableModel model;
    private INhanVienService iNhanVienService;
    private int totalNhanVien;
    private int totalPage;
    private int currentPage;
    private final int pageSize;

    public FrmNhanVien() {
        initComponents();
        setLocationRelativeTo(this);
        model = (DefaultTableModel) tblNhanVien.getModel();
        iCuaHangRepository = new CuaHangRepository();
        iChucVuRepository = new ChucVuRepository();
        iNhanVienService = new NhanVienService();
        iNhanVienRepository = new NhanVienRepository();
        pageSize = 5;
        currentPage = 1;
        getAllCuaHang();
        getAllChucVu();
        getAllNhanVien();
        loadTable(getCurrentPage());
    }

    private void getAllCuaHang() {
        model1 = (DefaultComboBoxModel<String>) cbxCuaHang.getModel();
        model1.removeAllElements();
        List<CuaHang> cuaHang = iCuaHangRepository.findAll();
        for (CuaHang ch : cuaHang) {
            model1.addElement(ch.getTen());
        }
    }

    private void getAllChucVu() {
        model1 = (DefaultComboBoxModel<String>) cbxChucvu.getModel();
        model1.removeAllElements();
        List<ChucVu> chucVus = iChucVuRepository.findAll();
        for (ChucVu cv : chucVus) {
            model1.addElement(cv.getTen());
        }
    }

    private void getAllNhanVien() {
        model1 = (DefaultComboBoxModel<String>) cbxIdGuiBC.getModel();
        model1.removeAllElements();
        model1.addElement("");
        List<QLNhanVien> nhanViens = iNhanVienService.getAllLNhanViens();
        for (QLNhanVien nv : nhanViens) {
            model1.addElement(nv.getTen());
        }
    }

    void loadTable(List<QLNhanVien> list) {
        model.setRowCount(0);
        for (QLNhanVien nv : list) {
            String idGuiBC;
            if (nv.getNhanVien() == null) {
                idGuiBC = "";
            } else {
                idGuiBC = nv.getNhanVien().getTen();
            }
            model.addRow(new Object[]{nv.getId(), nv.getMa(), nv.getTen(), nv.getTenDem(), nv.getHo(), nv.getGioiTinh(), nv.getNgaySinh(), nv.getDiaChi(),
                nv.getSdt(), nv.getMatKhau(), nv.getCuaHang().getTen(), nv.getChucVu().getTen(), idGuiBC, nv.getTrangThaiString()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField7 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        txtTenDem = new javax.swing.JTextField();
        txtHo = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtMK = new javax.swing.JTextField();
        btnNew = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        rbMale = new javax.swing.JRadioButton();
        rbFemale = new javax.swing.JRadioButton();
        btnTruoc = new javax.swing.JButton();
        lblCurrentPage = new javax.swing.JLabel();
        BtnSau = new javax.swing.JButton();
        lblTong = new javax.swing.JLabel();
        cbxCuaHang = new javax.swing.JComboBox<>();
        cbxChucvu = new javax.swing.JComboBox<>();
        cbxIdGuiBC = new javax.swing.JComboBox<>();
        btnClear = new javax.swing.JButton();
        rbTrangThai1 = new javax.swing.JRadioButton();
        rbTrangThai0 = new javax.swing.JRadioButton();
        txtID = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã:");

        jLabel2.setText("Tên:");

        jLabel3.setText("Tên đệm:");

        jLabel4.setText("Họ:");

        jLabel5.setText("Giới tính:");

        jLabel6.setText("Ngày sinh:");

        jLabel7.setText("Địa chỉ:");

        jLabel8.setText("SĐT:");

        jLabel9.setText("Mật khẩu:");

        jLabel10.setText("Cửa hàng:");

        jLabel11.setText("Chức Vụ:");

        jLabel12.setText("IdGuiBC:");

        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel14.setText("Trạng thái:");

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Mã", "Tên", "Tên đệm", "Họ", "Giới tính", "Ngày sinh", "Địa chỉ", "SĐT", "Mật khẩu", "IdCH", "IdCV", "IdGuiBC", "Trạng thái"
            }
        ));
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhanVien);

        buttonGroup1.add(rbMale);
        rbMale.setText("Nam");

        buttonGroup1.add(rbFemale);
        rbFemale.setText("Nữ");

        btnTruoc.setText("<");
        btnTruoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTruocActionPerformed(evt);
            }
        });

        lblCurrentPage.setText("1/1");

        BtnSau.setText(">");
        BtnSau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSauActionPerformed(evt);
            }
        });

        lblTong.setText("Tổng:");

        cbxCuaHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbxChucvu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbxIdGuiBC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbTrangThai1);
        rbTrangThai1.setText("đang hoạt động");

        buttonGroup2.add(rbTrangThai0);
        rbTrangThai0.setText("đã ngưng hoạt động");

        txtID.setEditable(false);

        jLabel13.setText("Id:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtMa, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                                            .addComponent(txtTen, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rbMale)
                                                .addGap(18, 18, 18)
                                                .addComponent(rbFemale)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtHo, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txtTenDem)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(111, 111, 111)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtMK, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                                            .addComponent(jLabel12))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(cbxIdGuiBC, 0, 148, Short.MAX_VALUE)
                                            .addComponent(cbxCuaHang, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbxChucvu, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbTrangThai1)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbTrangThai0))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(42, 42, 42)
                                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 46, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnTruoc, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(lblCurrentPage, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(BtnSau, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(lblTong, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cbxCuaHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(cbxChucvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(cbxIdGuiBC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(rbTrangThai1)
                            .addComponent(rbTrangThai0)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTenDem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(rbMale)
                            .addComponent(rbFemale))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNew)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnClear))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTruoc)
                    .addComponent(lblCurrentPage)
                    .addComponent(BtnSau)
                    .addComponent(lblTong))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        QLNhanVien nhanVien = validateNhanVien();
        if (nhanVien != null) {
            JOptionPane.showMessageDialog(this, iNhanVienService.createNewNhanVien(nhanVien));
            loadTable(getCurrentPage());
        }
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int selectRow = tblNhanVien.getSelectedRow();
        if (selectRow < 0) {
            JOptionPane.showMessageDialog(this, "Bạn cần chọn 1 Nhân Viên trên bảng");
            return;
        }
        QLNhanVien nhanVien = validateNhanVien();
        String id = model.getValueAt(selectRow, 0).toString();
        JOptionPane.showMessageDialog(this, iNhanVienService.updateNhanVien(nhanVien, id));
        loadTable(getCurrentPage());
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectRow = tblNhanVien.getSelectedRow();
        if (selectRow < 0) {
            JOptionPane.showMessageDialog(this, "Bạn cần chọn 1 Nhân Viên trên bảng");
            return;
        }
        String id = model.getValueAt(selectRow, 0).toString();
        int kq = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa không?", " Xác Nhận", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (kq == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, iNhanVienService.deleteNhanVien(id));
            loadTable(getCurrentPage());
            clear();
        } else {
            JOptionPane.showMessageDialog(this, "Xóa thất bại");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        // TODO add your handling code here:
        int selectRow = tblNhanVien.getSelectedRow();
        txtID.setText(tblNhanVien.getValueAt(selectRow, 0).toString());
        txtMa.setText(tblNhanVien.getValueAt(selectRow, 1).toString());
        txtTen.setText(tblNhanVien.getValueAt(selectRow, 2).toString());
        txtTenDem.setText(tblNhanVien.getValueAt(selectRow, 3).toString());
        txtHo.setText(tblNhanVien.getValueAt(selectRow, 4).toString());
        if (tblNhanVien.getValueAt(selectRow, 5).toString().equalsIgnoreCase("Nam")) {
            rbMale.setSelected(true);
        } else {
            rbFemale.setSelected(true);
        }
        txtNgaySinh.setText(tblNhanVien.getValueAt(selectRow, 6).toString());
        txtDiaChi.setText(tblNhanVien.getValueAt(selectRow, 7).toString());
        txtSDT.setText(tblNhanVien.getValueAt(selectRow, 8).toString());
        txtMK.setText(tblNhanVien.getValueAt(selectRow, 9).toString());
        cbxCuaHang.setSelectedItem(tblNhanVien.getValueAt(selectRow, 10));
        cbxChucvu.setSelectedItem(tblNhanVien.getValueAt(selectRow, 11));
        cbxIdGuiBC.setSelectedItem(tblNhanVien.getValueAt(selectRow, 12));
        if (tblNhanVien.getValueAt(selectRow, 13).toString().equalsIgnoreCase("đang hoạt động")) {
            rbTrangThai1.setSelected(true);
        } else {
            rbTrangThai0.setSelected(true);
        }
    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void BtnSauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSauActionPerformed
        // TODO add your handling code here:
        currentPage++;
        if (currentPage > totalPage) {
            currentPage = 1;
        }
        loadTable(getCurrentPage());
    }//GEN-LAST:event_BtnSauActionPerformed

    private void btnTruocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTruocActionPerformed
        // TODO add your handling code here:
        currentPage--;
        if (currentPage == 0) {
            currentPage = totalPage;
        }
        loadTable(getCurrentPage());
    }//GEN-LAST:event_btnTruocActionPerformed

    private QLNhanVien validateNhanVien() {
        String id = "";
        String ma = txtMa.getText();
        if (ma.isBlank()) {
            JOptionPane.showMessageDialog(this, "Bạn không được để trống MÃ");
            return null;
        }
        String ten = txtTen.getText();
        if (ten.isBlank()) {
            JOptionPane.showMessageDialog(this, "Bạn không được để trống Tên");
            return null;
        }
        String tenDem = txtTenDem.getText();
        if (ma.isBlank()) {
            JOptionPane.showMessageDialog(this, "Bạn không được để trống Tên đệm");
            return null;
        }
        String ho = txtHo.getText();
        if (ma.isBlank()) {
            JOptionPane.showMessageDialog(this, "Bạn không được để trống Họ");
            return null;
        }
        if (!rbMale.isSelected() && !rbFemale.isSelected()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn giới tính");
            return null;
        }
        String gTinh = (rbMale.isSelected() == true) ? "Nam" : "Nữ";
        String nSinh = txtNgaySinh.getText();
        if (nSinh.isBlank()) {
            JOptionPane.showMessageDialog(this, "Bạn không được để trống Ngày sinh");
            return null;
        }
        String diaChi = txtDiaChi.getText();
        if (diaChi.isBlank()) {
            JOptionPane.showMessageDialog(this, "Bạn không được để trống Địa chỉ");
            return null;
        }
        String sdt = txtSDT.getText();
        if (sdt.isBlank()) {
            JOptionPane.showMessageDialog(this, "Bạn không được để trống SĐT");
            return null;
        }
        String mK = txtMK.getText();
        if (mK.isBlank()) {
            JOptionPane.showMessageDialog(this, "Bạn không được để trống MK");
            return null;
        }
        String tenCH = (String) cbxCuaHang.getSelectedItem();
        CuaHang cuaHang = iCuaHangRepository.layCuaHangTheoTen(tenCH);
        String tenChucVu = (String) cbxChucvu.getSelectedItem();
        ChucVu chucVu = iChucVuRepository.layChucVuTheoTen(tenChucVu);
        NhanVien nhanVien;
        String tenNV = (String) cbxIdGuiBC.getSelectedItem();
        if (tenNV.equalsIgnoreCase("")) {
            nhanVien = null;
        } else {
            nhanVien = iNhanVienRepository.layNhanVienTheoName(tenNV);
        }
        if (!rbTrangThai1.isSelected() && !rbTrangThai0.isSelected()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn Trạng thái");
            return null;
        }
        String trangThaiString = (rbTrangThai1.isSelected() == true) ? rbTrangThai1.getText() : rbTrangThai0.getText();
        int trangThai = (trangThaiString.equalsIgnoreCase("đang hoạt động")) ? 1 : 0;
        return new QLNhanVien(id, ma, ten, tenDem, ho, gTinh, nSinh, diaChi, sdt, mK, cuaHang, chucVu, nhanVien, trangThai);
    }

    private void clear() {
        txtID.setText("");
        txtMa.setText("");
        txtTen.setText("");
        txtTenDem.setText("");
        txtHo.setText("");
        rbMale.setSelected(true);
        txtNgaySinh.setText("");
        txtDiaChi.setText("");
        txtSDT.setText("");
        txtMK.setText("");
        cbxCuaHang.setSelectedIndex(0);
        cbxChucvu.setSelectedIndex(0);
        cbxIdGuiBC.setSelectedIndex(0);
        rbTrangThai1.setSelected(true);
    }

    private List<QLNhanVien> getCurrentPage() {
        totalNhanVien = iNhanVienService.getAllLNhanViens().size();
        totalPage = (totalNhanVien - 1) / pageSize + 1;
        lblTong.setText("Tổng NhanVien:" + totalNhanVien);
        lblCurrentPage.setText(currentPage + "/" + totalPage);
        int start = (currentPage - 1) * pageSize;
        int end = currentPage * pageSize;
        if (end > totalNhanVien) {
            end = totalNhanVien;
        }
        return iNhanVienService.getAllLNhanViens().subList(start, end);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tubtnUpdateiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSau;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnTruoc;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbxChucvu;
    private javax.swing.JComboBox<String> cbxCuaHang;
    private javax.swing.JComboBox<String> cbxIdGuiBC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel lblCurrentPage;
    private javax.swing.JLabel lblTong;
    private javax.swing.JRadioButton rbFemale;
    private javax.swing.JRadioButton rbMale;
    private javax.swing.JRadioButton rbTrangThai0;
    private javax.swing.JRadioButton rbTrangThai1;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtHo;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMK;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTenDem;
    // End of variables declaration//GEN-END:variables

}
